// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	afxdpMapXsksMap              = "xsks_map"
	afxdpProgXdpRedirectToSocket = "xdp_redirect_to_socket"
)

// loadAfxdp returns the embedded CollectionSpec for afxdp.
func loadAfxdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AfxdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load afxdp: %w", err)
	}

	return spec, err
}

// loadAfxdpObjects loads afxdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*afxdpObjects
//	*afxdpPrograms
//	*afxdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAfxdpObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadAfxdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// afxdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type afxdpSpecs struct {
	afxdpProgramSpecs
	afxdpMapSpecs
	afxdpVariableSpecs
}

// afxdpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type afxdpProgramSpecs struct {
	XdpRedirectToSocket *ebpf.ProgramSpec `ebpf:"xdp_redirect_to_socket"`
}

// afxdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type afxdpMapSpecs struct {
	XsksMap *ebpf.MapSpec `ebpf:"xsks_map"`
}

// afxdpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type afxdpVariableSpecs struct {
}

// afxdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAfxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type afxdpObjects struct {
	afxdpPrograms
	afxdpMaps
	afxdpVariables
}

func (o *afxdpObjects) Close() error {
	return _AfxdpClose(
		&o.afxdpPrograms,
		&o.afxdpMaps,
	)
}

// afxdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAfxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type afxdpMaps struct {
	XsksMap *ebpf.Map `ebpf:"xsks_map"`
}

func (m *afxdpMaps) Close() error {
	return _AfxdpClose(
		m.XsksMap,
	)
}

// afxdpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAfxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type afxdpVariables struct {
}

// afxdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAfxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type afxdpPrograms struct {
	XdpRedirectToSocket *ebpf.Program `ebpf:"xdp_redirect_to_socket"`
}

func (p *afxdpPrograms) Close() error {
	return _AfxdpClose(
		p.XdpRedirectToSocket,
	)
}

func _AfxdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed afxdp_bpfeb.o
var _AfxdpBytes []byte
